// import { useState } from "react";
import { motion as Motion } from "framer-motion";
import { FaBook, FaPuzzlePiece, FaPlay, FaExclamationTriangle, FaLightbulb, FaRobot } from "react-icons/fa"; // Added FaRobot, FaLightbulb


const TopicInputScreen = ({ topic, setTopic, difficulty, setDifficulty, startQuiz, error }) => {

    const difficulties = ["Easy", "Medium", "Hard"];

    // Variants for the entire TopicInputScreen component to animate in
    const screenVariants = {
        initial: { opacity: 0, y: 50 },
        animate: { 
            opacity: 1, 
            y: 0, 
            transition: { 
                duration: 0.7, 
                ease: "easeOut",
                staggerChildren: 0.1 // Stagger the main sections
            } 
        },
        exit: { opacity: 0, y: -50, transition: { duration: 0.5, ease: "easeIn" } }
    };

    // Variants for items *within* the card for staggered animation
    const cardItemVariants = {
        initial: { opacity: 0, y: 20 },
        animate: { opacity: 1, y: 0, transition: { duration: 0.4, ease: "easeOut" } }
    };

    return (
        <Motion.div
            variants={screenVariants}
            initial="initial"
            animate="animate"
            exit="exit"
            className="w-full h-full flex flex-col md:flex-row items-center justify-center p-4 md:p-8"
        >
            {/* Left Section: 3D Model Placeholder (Smaller, 1/3 or 2/5 width) */}
            <Motion.div 
                variants={cardItemVariants} // Apply item animation to this section too
                className="w-full md:w-2/5 lg:w-1/3 flex flex-col items-center justify-center p-6 md:p-0 mb-8 md:mb-0 md:mr-12 text-center"
            >
                {/* Placeholder for 3D Model */}
                <div className="relative w-full max-w-sm h-64 md:h-96 bg-gradient-to-br from-purple-800 to-fuchsia-700 rounded-3xl shadow-2xl flex items-center justify-center mb-6 ring-4 ring-fuchsia-400/20"
                     style={{
                         transformStyle: "preserve-3d",
                         transform: "perspective(1000px) rotateY(10deg) rotateX(5deg)", // Subtle 3D tilt
                         filter: "drop-shadow(0 0 20px rgba(192, 38, 211, 0.6))"
                     }}>
                    <FaRobot className="text-fuchsia-300 text-8xl absolute z-10 animate-pulse-slow" />
                    <div className="absolute inset-0 bg-black/30 rounded-3xl"></div>
                    <div className="absolute w-3/4 h-3/4 bg-fuchsia-500/20 rounded-full blur-xl animate-blob"></div>
                    <p className="absolute bottom-6 text-fuchsia-200 font-semibold text-xl tracking-wider">
                        Your 3D Model Here
                    </p>
                </div>
                <h3 className="text-3xl font-extrabold text-white leading-tight drop-shadow-[0_0_8px_rgba(255,255,255,0.2)]">
                    <span className="text-cyan-400">BRAIN</span><span className="text-fuchsia-400">WAVE</span> AI
                </h3>
                <p className="text-gray-400 text-lg mt-2 max-w-xs">
                    Unleash your potential with personalized quizzes generated by advanced AI.
                </p>
            </Motion.div>

            {/* Right Section: Quiz Input Card (Larger, 2/3 or 3/5 width) */}
            <Motion.div
                variants={cardItemVariants} // Apply item animation to this section too
                className="quiz-input-card text-center p-8 sm:p-12 bg-gray-800/20 border border-gray-700/40 rounded-[3rem] shadow-2xl backdrop-blur-xl w-full md:w-3/5 lg:w-2/3 max-w-2xl ring-4 ring-cyan-400/10 flex flex-col justify-center"
                style={{
                    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)', // Glassmorphism shadow
                    minHeight: '500px' // Ensure it has a decent height
                }}
            >
                <Motion.h2 
                    variants={cardItemVariants} // Stagger this element within the card
                    className="text-4xl font-extrabold text-white mb-8 drop-shadow-[0_0_8px_rgba(255,255,255,0.2)]"
                >
                    Generate Your Quiz
                </Motion.h2>

                <Motion.div variants={cardItemVariants} className="w-full mb-6">
                    <label htmlFor="topic-input" className="sr-only">Quiz Topic</label>
                    <div className="relative">
                        <FaBook className="absolute left-4 top-1/2 -translate-y-1/2 text-fuchsia-400 text-xl" />
                        <input
                            id="topic-input"
                            type="text"
                            value={topic}
                            onChange={(e) => setTopic(e.target.value)}
                            placeholder="e.g., Quantum Physics, Renaissance Art, Python"
                            className="w-full p-4 pl-12 bg-gray-900/70 border border-gray-700 rounded-xl text-white placeholder-gray-400 focus:ring-2 focus:ring-fuchsia-500 focus:border-transparent outline-none transition-all duration-300 shadow-lg text-lg"
                        />
                    </div>
                </Motion.div>

                <Motion.div variants={cardItemVariants} className="w-full mb-8">
                    <h3 className="text-xl font-semibold text-gray-300 mb-4">Select Difficulty:</h3>
                    <div className="grid grid-cols-3 gap-4">
                        {difficulties.map((level) => (
                            <Motion.button
                                key={level}
                                onClick={() => setDifficulty(level)}
                                whileHover={{ scale: 1.05, boxShadow: '0 0 15px rgba(139, 92, 246, 0.4)' }}
                                whileTap={{ scale: 0.95 }}
                                className={`p-4 rounded-xl font-bold text-lg transition-all duration-300 flex items-center justify-center
                                    ${difficulty === level
                                        ? "bg-fuchsia-600 text-white shadow-xl shadow-fuchsia-600/50 ring-2 ring-fuchsia-400"
                                        : "bg-gray-800/70 text-gray-300 border border-gray-700 hover:bg-gray-700/80"
                                    }`}
                            >
                                <FaPuzzlePiece className="mr-2" /> {level}
                            </Motion.button>
                        ))}
                    </div>
                </Motion.div>

                {error && (
                    <Motion.div 
                        variants={cardItemVariants}
                        className="flex items-center text-red-400 mb-6 p-3 bg-red-900/30 border border-red-700 rounded-lg"
                    >
                        <FaExclamationTriangle className="mr-2" />
                        <p className="text-sm italic">{error}</p>
                    </Motion.div>
                )}

                <Motion.button
                    variants={cardItemVariants}
                    onClick={startQuiz}
                    whileHover={{ scale: 1.05, boxShadow: '0 0 20px rgba(52, 211, 255, 0.6)' }}
                    whileTap={{ scale: 0.95 }}
                    className="mt-4 bg-gradient-to-r from-cyan-500 to-blue-600 text-gray-950 text-xl font-semibold px-10 py-4 rounded-2xl transition duration-300 shadow-xl shadow-cyan-500/50 flex items-center justify-center relative overflow-hidden"
                >
                    <FaPlay className="mr-3" /> Start Quiz
                </Motion.button>
            </Motion.div>
        </Motion.div>
    );
};

export default TopicInputScreen;